// constants.js
exports.META_START = '_META_START_'
exports.META_END = '_META_END_'
exports.COLUMNS_CATEGORIES = 'COLUMNS_CATEGORIES'
exports.NAME = 'NAME'
exports.CODE = 'CODE'
exports.INTAKE_DATETIME = 'INTAKE_DATETIME'
exports.TOTAL_AMOUNT = 'TOTAL_AMOUNT'
exports.COLUMNS = 'COLUMNS'
